# Generated by Django 3.0.5 on 2020-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Times',
        ),
    ]
